# Generated by Django 4.1.4 on 2023-01-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_fees_alter_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='due_fees',
            field=models.IntegerField(default='200'),
        ),
        migrations.AddField(
            model_name='student',
            name='paid_fees',
            field=models.IntegerField(default='100'),
        ),
        migrations.AlterField(
            model_name='fees',
            name='Class',
            field=models.IntegerField(unique=True),
        ),
    ]
