# Generated by Django 4.1.4 on 2023-01-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_due_fees_student_paid_fees_alter_fees_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='due_fees',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='student',
            name='paid_fees',
            field=models.IntegerField(default='0'),
        ),
    ]
